apiVersion: v1
kind: ReplicationController
metadata:
  name: phpapprc
spec:
  replicas: 1
  selector:
    app: phpapp
  template:
    metadata:
      name: phpapppod
      labels:
        app: phpapp
    spec:
      containers:
        - name: phpappcontainer
          image: adv4000/k8sphp:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: phpappsvc
spec:
  type: NodePort
  selector:
    app: phpapp
  ports:
    - port: 80
      targetPort: 8080
