apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: filestore-nfs-pv
