apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-binding
  namespace: aidana
subjects:
  - kind: ServiceAccount
    name: my-svaccount
    namespace: aidana
roleRef:
  kind: Role
  name: read-only
  apiGroup: rbac.authorization.k8s.io
